### ISSUE TITLE
Training LLMs such as BERT

### ISSUE THREAD

**Issue by KongMingxi** [Liuhong99/Sophia#12]
Hi there,

Congrats and thanks for your excellent work!

I am wondering if Sophia can be used to train other LLMs such as BERT? Will it also reduce computing overhead?

In addition, can I use Sophia with the pytorch 1.13.1?

Best,

Mx

**Comment by lessw2020** [comment]
Hi @KongMingxi,
Just wanted to note that from reviewing the code, Sophia is not generally dependent on a specific PyTorch version as it's not using version specific functions in it's algo.
1.13.x should work fine, as does the latest nightlies which is what I used (dev 2.0.today's_date)

Also, I tested Sophia on a ViT and it worked well, so no reason to suspect it won't do well on Bert, t5, etc. since it's optimization algo is independent of model architecture.

Hope that helps,
Less

**Comment by KongMingxi** [comment]
> Just wanted to note that from reviewing the code, Sophia is not generally dependent on a specific PyTorch version as it's not using version specific functions in it's algo. 1.13.x should work fine, as does the latest nightlies which is what I used (dev 2.0.today's_date)
> 
> Also, I tested Sophia on a ViT and it worked well, so no reason to suspect it won't do well on Bert, t5, etc. since it's optimization algo is independent of model architecture.

Thanks for your kind help, Less! I'll give it a try

**Comment by Liuhong99** [comment]
Thanks Less for the reply! 
Thanks @KongMingxi for raising this question! We'd like to hear what you find!
