### ISSUE TITLE
Does this work with 16-mixed precision

### ISSUE THREAD

**Issue by tkella47** [Liuhong99/Sophia#16]
I have been trying to use Sophia-G with 16-mixed precision, but I eventually encounter a loss scaling error. 
`
Exception: Current loss scale already at minimum - cannot decrease scale`

**Comment by tkella47** [comment]
I find that with 16-mixed precision, the optimizer eventually leads to nan loss.

**Comment by lessw2020** [comment]
@tkella47  - can you provide more details, or since it seems you mean FP16, switch to BF16?  
16-mixed precision could be FP16, BFloat16 and impl for mixed precision varies depending on if you are using FSDP vs torch.amp, etc.
I have trained using BF16 and Sophia with no issues.
Given the scaling error, it seems you are using FP16 which inherently is not something I would recommend generically - BF16 does not need any scaling and so you are not having the grad scalar playing guessing games during training.
If FP16 is a must, then you may need to adapt (reduce) your LR and/or scheduler to lighten up to avoid the NaN issue.

**Comment by tkella47** [comment]
Ah thank for the feedback. I am experimenting with float point precision. I realized I am indeed  AMP with FP16. I will give it a try with BF16

**Comment by tkella47** [comment]
> @tkella47 - can you provide more details, or since it seems you mean FP16, switch to BF16? 16-mixed precision could be FP16, BFloat16 and impl for mixed precision varies depending on if you are using FSDP vs torch.amp, etc. I have trained using BF16 and Sophia with no issues. Given the scaling error, it seems you are using FP16 which inherently is not something I would recommend generically - BF16 does not need any scaling and so you are not having the grad scalar playing guessing games during training. If FP16 is a must, then you may need to adapt (reduce) your LR and/or scheduler to lighten up to avoid the NaN issue.

Thanks for the feedback. I am experimenting with float point precision and realized I am indeed AMP with FP16. I will give it a try with BF16.
