### ISSUE TITLE
i think it is similar than rmsprop

### ISSUE THREAD

**Issue by YooSungHyun** [Liuhong99/Sophia#52]
loss moving graph in paper, it looks like rmsprop
how about your opinion? it is better than rmsprop, and why?

**Comment by Liuhong99** [comment]
Thanks for the interest in Sophia! Sophia is different from RMSprop because (1) Sophia has the second-order estimator in the denominator, while RMSprop uses the square root of exponential moving average of squared gradients. (2) RMSprop does not have the moving average in the numerator of the update rule.  To further help address your question, which loss moving graph are you referring to?
